"""LLM layer for the DBAG AI Playground API (client, config, models, costs, utils)."""

from __future__ import annotations

from .client import (
    ask,
    chat,
    embeddings,
    get_openai_client,
    get_token_usage,
    list_models,
    stream_chat,
)
from .config import ConfigError, has_api_key
from .costs import (
    CallRecord,
    CostsConfigError,
    Price,
    RunTracker,
    cost_weight,
    estimate_cost,
    estimate_usd,
    load_costs,
    price_for,
    reload_costs,
    usd_price,
)
from .models import (
    CHAT_MODELS,
    CLAUDE_MODELS,
    DATABRICKS_CHAT_ENDPOINTS,
    DATABRICKS_EMBEDDING_ENDPOINTS,
    DATABRICKS_ENDPOINTS,
    DEFAULT_CHAT_MODEL,
    DEFAULT_EMBEDDING_MODEL,
    EMBEDDING_MODELS,
    GEMINI_MODELS,
    GPT_MODELS,
    OTHER_MODELS,
    family,
    is_claude,
)
from .utils import (
    PlaygroundError,
    extract_text,
    extract_usage,
    format_usage,
    get_error_message,
    is_error,
    print_response,
)

__all__ = [
    "ask",
    "chat",
    "embeddings",
    "get_openai_client",
    "get_token_usage",
    "list_models",
    "stream_chat",
    "ConfigError",
    "has_api_key",
    "CallRecord",
    "CostsConfigError",
    "Price",
    "RunTracker",
    "cost_weight",
    "estimate_cost",
    "estimate_usd",
    "load_costs",
    "price_for",
    "reload_costs",
    "usd_price",
    "CHAT_MODELS",
    "CLAUDE_MODELS",
    "GEMINI_MODELS",
    "GPT_MODELS",
    "OTHER_MODELS",
    "EMBEDDING_MODELS",
    "DATABRICKS_CHAT_ENDPOINTS",
    "DATABRICKS_EMBEDDING_ENDPOINTS",
    "DATABRICKS_ENDPOINTS",
    "DEFAULT_CHAT_MODEL",
    "DEFAULT_EMBEDDING_MODEL",
    "family",
    "is_claude",
    "PlaygroundError",
    "extract_text",
    "extract_usage",
    "format_usage",
    "get_error_message",
    "is_error",
    "print_response",
]
